const restaurants = [
  {
    "address": "خیابان اصلی، کوچه ۱",
    "adminPassword": "رمزادمین1",
    "adminUserName": "admin1",
    "comments": [],
    "description": "رستوران گلابی",
    "isApproval": false,
    "menu": [],
    "name": "آشپزخانه گلاب",
    "score": 8.2,
    "createdAt": "2024-02-01T10:30:00Z",
    "updatedAt": "2024-02-01T10:30:00Z"
  },
  {
    "address": "خیابان اصلی، کوچه ۲",
    "adminPassword": "رمزادمین2",
    "adminUserName": "admin2",
    "comments": [],
    "description": "رستوران سبز",
    "isApproval": false,
    "menu": [],
    "name": "لذت طعم",
    "score": 7.6,
    "createdAt": "2024-02-02T11:45:00Z",
    "updatedAt": "2024-02-02T11:45:00Z"
  },
  {
    "address": "خیابان اصلی، کوچه ۳",
    "adminPassword": "رمزادمین3",
    "adminUserName": "admin3",
    "comments": [],
    "description": "رستوران خوشرنگ",
    "isApproval": false,
    "menu": [],
    "name": "سفر به طعم",
    "score": 9.0,
    "createdAt": "2024-02-03T12:15:00Z",
    "updatedAt": "2024-02-03T12:15:00Z"
  },
  {
    "address": "خیابان اصلی، کوچه ۴",
    "adminPassword": "رمزادمین4",
    "adminUserName": "admin4",
    "comments": [],
    "description": "رستوران نارنج",
    "isApproval": false,
    "menu": [],
    "name": "نارنجی",
    "score": 6.8,
    "createdAt": "2024-02-04T14:20:00Z",
    "updatedAt": "2024-02-04T14:20:00Z"
  },
  {
    "address": "خیابان اصلی، کوچه ۵",
    "adminPassword": "رمزادمین5",
    "adminUserName": "admin5",
    "comments": [],
    "description": "رستوران مازندرانی",
    "isApproval": false,
    "menu": [],
    "name": "آشپزی مازندران",
    "score": 8.5,
    "createdAt": "2024-02-05T15:30:00Z",
    "updatedAt": "2024-02-05T15:30:00Z"
  },
  {
    "address": "خیابان اصلی، کوچه ۶",
    "adminPassword": "رمزادمین6",
    "adminUserName": "admin6",
    "comments": [],
    "description": "رستوران خوشمزه",
    "isApproval": false,
    "menu": [],
    "name": "خوشمزه",
    "score": 7.3,
    "createdAt": "2024-02-06T16:45:00Z",
    "updatedAt": "2024-02-06T16:45:00Z"
  },
  {
    "address": "خیابان اصلی، کوچه ۷",
    "adminPassword": "رمزادمین7",
    "adminUserName": "admin7",
    "comments": [],
    "description": "رستوران دلپذیر",
    "isApproval": false,
    "menu": [],
    "name": "دلپذیر",
    "score": 9.1,
    "createdAt": "2024-02-07T18:00:00Z",
    "updatedAt": "2024-02-07T18:00:00Z"
  },
  {
    "address": "خیابان اصلی، کوچه ۸",
    "adminPassword": "رمزادمین8",
    "adminUserName": "admin8",
    "comments": [],
    "description": "رستوران آسیایی",
    "isApproval": false,
    "menu": [],
    "name": "طعم آسیایی",
    "score": 6.5,
    "createdAt": "2024-02-08T20:10:00Z",
    "updatedAt": "2024-02-08T20:10:00Z"
  },
  {
    "address": "خیابان اصلی، کوچه ۹",
    "adminPassword": "رمزادمین9",
    "adminUserName": "admin9",
    "comments": [],
    "description": "رستوران لحظه لذت",
    "isApproval": false,
    "menu": [],
    "name": "لحظه لذت",
    "score": 8.9,
    "createdAt": "2024-02-09T22:30:00Z",
    "updatedAt": "2024-02-09T22:30:00Z"
  },
  {
    "address": "خیابان اصلی، کوچه ۱۰",
    "adminPassword": "رمزادمین10",
    "adminUserName": "admin10",
    "comments": [],
    "description": "رستوران خوراک خوب",
    "isApproval": false,
    "menu": [],
    "name": "خوراک خوب",
    "score": 7.7,
    "createdAt": "2024-02-10T23:45:00Z",
    "updatedAt": "2024-02-10T23:45:00Z"
  }
]

module.exports = restaurants